name: 'Deploy to DOKS'
description: 'Deploy image from Digital Ocean Repository to DOKS using k8s manifests'
inputs:
  manifests:
    description: 'Where are located manifest files to deploy'
    required: true
  cluster:
    description: 'Name of the cluster in Digital Ocean'
    required: true
  accessToken:
    description: 'Digital Ocean API Access Token'
    required: true
  repository:
    description: 'Digital Ocean Repository'
    required: true
  tag:
    description: 'Tag to use'
runs:
  using: "composite"
  steps:
      - uses: action-digitalocean-k8s-manifests-update@main
        with:
          manifests: ${{ inputs.manifests }}
          repository: ${{ inputs.repository }}
          tag: ${{ inputs.tag }}

      - uses: action-digitalocean-k8s-kubectl@main
        with:
          kubectl: apply -R -f $GITHUB_WORKSPACE/${{ inputs.manifests }}
          cluster: ${{ inputs.cluster }}
          accessToken: ${{ inputs.accessToken }}
