name: 'Deploy to DOKS'
description: 'Deploy image from Digital Ocean Repository to DOKS using k8s manifests'
inputs:
  manifests:
    description: 'Where are located manifest files to deploy'
    required: true
  cluster:
    description: 'Name of the cluster in Digital Ocean'
    required: true
  accessToken:
    description: 'Digital Ocean API Access Token'
    required: true
  repository:
    description: 'Digital Ocean Repository'
    required: true
  tag:
    description: 'Tag to use'
runs:
  using: "composite"
  steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ inputs.accessToken }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Prepare manifests
        uses: Slidem/inplace-envsubst-action@v1.2.2
        env:
          IMAGE: registry.digitalocean.com/${{ inputs.repository }}:${{ inputs.tag || steps.short-sha.outputs.sha }}
        with:
          working-directory: ${{ inputs.manifests }}
          fail_on_missing_variables: false
          search_input: |
            {
              "patterns": [".+.yaml", ".+.yml"],
              "depth": 2
            }

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ inputs.cluster }}
        shell: bash

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/${{ inputs.manifests }}
        shell: bash
